# Generated by Django 3.0.6 on 2023-02-06 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('cpf', models.CharField(blank=True, max_length=14, unique=True, verbose_name='CPF')),
                ('cnpj', models.CharField(blank=True, max_length=18, unique=True, verbose_name='CNPJ')),
                ('telefone', models.CharField(blank=True, max_length=18, unique=True, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=200, verbose_name='email')),
                ('endereco', models.CharField(blank=True, max_length=200, verbose_name='Endereço')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, null=True, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Modelo_Gerador', models.CharField(blank=True, choices=[('Carenado', (('Slim 40 kVA Carenado/Silenciado', 'Slim 40 kVA Carenado/Silenciado'), ('Slim 55 kVA Carenado/Silenciado', 'Slim 55 kVA Carenado/Silenciado'), ('Slim 60 kVA Carenado/Silenciado', 'Slim 60 kVA Carenado/Silenciado'), ('Slim 63 kVA Carenado/Silenciado', 'Slim 63kVA Carenado/Silenciado'), ('Slim 75 kVA Carenado/Silenciado', 'Slim 75kVA Carenado/Silenciado'), ('Slim 95 kVA Carenado/Silenciado', 'Slim 95 kVA Carenado/Silenciado'), ('Slim 83 kVA Carenado/Silenciado', 'Slim 83 kVA Carenado/Silenciado'), ('Slim 100 kVA  Carenado/Silenciado', 'Slim 100 kVA Carenado/Silenciado'), ('Slim 110 kVA Carenado/Silenciado', 'Slim 110 kVA Carenado/Silenciado'), ('Slim 123 kVA Carenado/Silenciado', 'Slim 123 kVA Carenado/Silenciado'), ('Slim 125 kVA  Carenado/Silenciado', 'Slim 125 kVA Carenado/Silenciado'), ('Slim 140 kVA Carenado/Silenciado', 'Slim 140 kVA Carenado/Silenciado'), ('Slim 207 kVA Carenado/Silenciado', 'Slim 207 kVA Carenado/Silenciado'), ('Slim 251 kVA Carenado/Silenciado', 'Slim 251 kVA Carenado/Silenciado'), ('Slim 300 kVA Carenado/Silenciado', 'Slim 300 kVA Carenado/Silenciado'), ('Slim 300 KVA  Carenado/Silenciado', 'Slim 300 KVA  Carenado/Silenciado'), ('Slim 330 KVA  Carenado/Silenciado', 'Slim 330 KVA  Carenado/Silenciado'), ('Slim 360 KVA  Carenado/Silenciado', 'Slim 360 KVA  Carenado/Silenciado'), ('Slim 400 KVA  Carenado/Silenciado', 'Slim 400 KVA  Carenado/Silenciado'), ('Slim 369 kVA Carenado/Silenciado', 'Slim 369 kVA Carenado/Silenciado'), ('Slim 285 kVA Carenado/Silenciado', 'Slim 285 kVA Carenado/Silenciado'), ('Slim 334 kVA Carenado/Silenciado', 'Slim 334 kVA Carenado/Silenciado'), ('Slim 350 kVA Carenado/Silenciado', 'Slim 350 kVA Carenado/Silenciado'), ('Slim 438 kVA Carenado/Silenciado', 'Slim 438 kVA Carenado/Silenciado'), ('Slim 450 kVA Carenado/Silenciado', 'Slim 450 kVA Carenado/Silenciado'), ('Slim 451 kVA Carenado/Silenciado', 'Slim 451 kVA Carenado/Silenciado'), ('Slim 500 kVA Carenado/Silenciado', 'Slim 500 kVA Carenado/Silenciado'), ('Slim 501 kVA Carenado/Silenciado', 'Slim 501 kVA Carenado/Silenciado'), ('Slim 550 kVA Carenado/Silenciado', 'Slim 550 kVA Carenado/Silenciado'), ('Slim 625 kVA Carenado/Silenciado', 'Slim 625 kVA Carenado/Silenciado'), ('Slim 650 kVA Carenado/Silenciado', 'Slim 650 kVA Carenado/Silenciado'), ('Slim 550 kVA Carenado/Silenciado', 'Slim 550 kVA Carenado/Silenciado'), ('Slim 625 kVA Carenado/Silenciado', 'Slim 625 kVA Carenado/Silenciado'), ('Slim 563 kVA Carenado/Silenciado', 'Slim 563 kVA Carenado/Silenciado'), ('Slim 642 kVA Carenado/Silenciado', 'Slim 642 kVA Carenado/Silenciado'), ('Slim 700 kVA Carenado/Silenciado', 'Slim 700 kVA Carenado/Silenciado'), ('Slim 720 kVA Carenado/Silenciado', 'Slim 720 kVA Carenado/Silenciado'), ('Slim 752 kVA Carenado/Silenciado', 'Slim 752 kVA Carenado/Silenciado'), ('Slim 770 kVA Carenado/Silenciado', 'Slim 770 kVA Carenado/Silenciado'), ('Slim 800 kVA Carenado/Silenciado', 'Slim 800 kVA Carenado/Silenciado'), ('Slim 800 kVA Carenado/Silenciado', 'Slim 800 kVA Carenado/Silenciado'), ('Slim 1100 kVA Carenado/Silenciado', 'Slim 1100 kVA Carenado/Silenciado'), ('Slim 1250 kVA Carenado/Silenciado', 'Slim 1250 kVA Carenado/Silenciado'), ('Slim 1000 kVA Carenado/Silenciado', 'Slim 1000 kVA Carenado/Silenciado'), ('Slim 1100 kVA Carenado/Silenciado', 'Slim 1100 kVA Carenado/Silenciado'), ('Slim 1250 kVA Carenado/Silenciado', 'Slim 1250 kVA Carenado/Silenciado'), ('Slim 1400 kVA Carenado/Silenciado', 'Slim 1400 kVA Carenado/Silenciado'), ('Slim 1500 kVA Carenado/Silenciado', 'Slim 1500 kVA Carenado/Silenciado'), ('Slim 1600 kVA Carenado/Silenciado', 'Slim 1600 kVA Carenado/Silenciado'), ('Slim 1600 kVA Carenado/Silenciado', 'Slim 1600 kVA Carenado/Silenciado'))), ('Alvenaria', (('Slim 40 kVA Alvenaria', 'Slim 40 kVA Alvenaria'), ('Slim 55 kVA Alvenaria', 'Slim 55 kVA Alvenaria'), ('Slim 60 kVA Alvenaria', 'Slim 60 kVA Alvenaria'), ('Slim 63kVA Alvenaria', 'Slim 63kVA Alvenaria'), ('Slim 75kVA Alvenaria', 'Slim 75kVA Alvenaria'), ('Slim 75 kVA Alvenaria', 'Slim 75 kVA Alvenaria'), ('Slim 95 kVA Alvenaria', 'Slim 95 kVA Alvenaria'), ('Slim 83 kVA Alvenaria', 'Slim 83 kVA Alvenaria'), ('Slim 100 kVA Alvenaria', 'Slim 100 kVA Alvenaria'), ('Slim 110 kVA Alvenaria', 'Slim 110 kVA Alvenaria'), ('Slim 123 kVA Alvenaria', 'Slim 123 kVA Alvenaria'), ('Slim 125 kVA Alvenaria', 'Slim 125 kVA Alvenaria'), ('Slim 140 kVA Alvenaria', 'Slim 140 kVA Alvenaria'), ('Slim 207 kVA Alvenaria', 'Slim 207 kVA Alvenaria'), ('Slim 251 kVA Alvenaria', 'Slim 251 kVA Alvenaria,'), ('Slim 300 kVA Alvenaria', 'Slim 300 kVA Alvenaria,'), ('Slim 300 KVA  Alvenaria', 'Slim 300 KVA  Alvenaria,'), ('Slim 330 KVA  Alvenaria', 'Slim 330 KVA  Alvenaria,'), ('Slim 360 KVA  Alvenaria', 'Slim 360 KVA  Alvenaria,'), ('Slim 400 KVA  Alvenaria', 'Slim 400 KVA  Alvenaria,'), ('Slim 369 kVA Alvenaria', 'Slim 369 kVA Alvenaria,'), ('Slim 285 kVA Alvenaria', 'Slim 285 kVA Alvenaria,'), ('Slim 334 kVA Alvenaria', 'Slim 334 kVA Alvenaria,'), ('Slim 350 kVA Alvenaria', 'Slim 350 kVA Alvenaria,'), ('Slim 438 kVA Alvenaria', 'Slim 438 kVA Alvenaria,'), ('Slim 450 kVA Alvenaria', 'Slim 450 kVA Alvenaria,'), ('Slim 451 kVA Alvenaria', 'Slim 451 kVA Alvenaria,'), ('Slim 500 kVA Alvenaria', 'Slim 500 kVA Alvenaria,'), ('Slim 501 kVA Alvenaria', 'Slim 501 kVA Alvenaria,'), ('Slim 550 kVA Alvenaria', 'Slim 550 kVA Alvenaria,'), ('Slim 625 kVA Alvenaria', 'Slim 625 kVA Alvenaria,'), ('Slim 650 kVA Alvenaria', 'Slim 650 kVA Alvenaria,'), ('Slim 550 kVA Alvenaria', 'Slim 550 kVA Alvenaria,'), ('Slim 625 kVA Alvenaria', 'Slim 625 kVA Alvenaria,'), ('Slim 563 kVA Alvenaria', 'Slim 563 kVA Alvenaria,'), ('Slim 642 kVA Alvenaria', 'Slim 642 kVA Alvenaria,'), ('Slim 700 kVA Alvenaria', 'Slim 700 kVA Alvenaria,'), ('Slim 720 kVA Alvenaria', 'Slim 720 kVA Alvenaria,'), ('Slim 752 kVA Alvenaria', 'Slim 752 kVA Alvenaria,'), ('Slim 770 kVA Alvenaria', 'Slim 770 kVA Alvenaria,'), ('Slim 800 kVA Alvenaria', 'Slim 800 kVA Alvenaria,'), ('Slim 800 kVA Alvenaria', 'Slim 800 kVA Alvenaria,'), ('Slim 1100 kVA Alvenaria', 'Slim 1100 kVA Alvenaria,'), ('Slim 1250 kVA Alvenaria', 'Slim 1250 kVA Alvenaria,'), ('Slim 1000 kVA Alvenaria', 'Slim 1000 kVA Alvenaria,'), ('Slim 1100 kVA Alvenaria', 'Slim 1100 kVA Alvenaria,'), ('Slim 1250 kVA Alvenaria', 'Slim 1250 kVA Alvenaria,'), ('Slim 1400 kVA Alvenaria', 'Slim 1400 kVA Alvenaria,'), ('Slim 1500 kVA Alvenaria', 'Slim 1500 kVA Alvenaria,'), ('Slim 1600 kVA Alvenaria', 'Slim 1600 kVA Alvenaria,'), ('Slim 1600 kVA Alvenaria', 'Slim 1600 kVA Alvenaria,')))], max_length=200)),
                ('Fabricante_Motor', models.CharField(blank=True, choices=[('Perkins', 'Perkins'), ('FPT', 'FPT'), ('CUMMINS', 'CUMMINS'), ('MWM', 'MWM'), ('Scania', 'Scania'), ('Volvo', 'Volvo')], max_length=200)),
                ('Modelo_Motor', models.CharField(max_length=100, verbose_name='Modelo Motor')),
                ('Içamento', models.CharField(choices=[('Único', 'Único'), ('Duplo', 'Duplo')], default='Único', max_length=100, verbose_name='Içamento')),
                ('Tanque_de_combustivel', models.CharField(max_length=100, verbose_name='Tanque de combustivel')),
                ('Dimensoes', models.CharField(blank=True, max_length=100, verbose_name='Dimensões')),
                ('Peso', models.CharField(blank=True, max_length=100, verbose_name='Peso')),
            ],
            options={
                'verbose_name': 'Motor',
                'verbose_name_plural': 'Motores',
            },
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ordem', models.CharField(max_length=20, unique=True, verbose_name='Número da proposta')),
                ('revisão', models.CharField(default='001', max_length=20, verbose_name='Revisão')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('Condições_de_Pagamento', models.CharField(choices=[('1x sem juros', '1x sem juros'), ('2x sem juros', '2x sem juros'), ('3x sem juros', '3x sem juros'), ('4x sem juros', '4x sem juros'), ('5x sem juros', '5x sem juros'), ('6x (2,3% juros ao mês)', '6x (2,3% juros ao mês)'), ('7x (2,3% juros ao mês)', '7x (2,3% juros ao mês)'), ('8x (2,3% juros ao mês)', '8x (2,3% juros ao mês)'), ('9x (2,3% juros ao mês)', '9x (2,3% juros ao mês)'), ('10x (2,3% juros ao mês)', '10x (2,3% juros ao mês)'), ('11x (2,3% juros ao mês)', '11x (2,3% juros ao mês)'), ('12x (2,3% juros ao mês)', '12x (2,3% juros ao mês)')], max_length=100)),
                ('validade', models.CharField(blank=True, choices=[('Cinco', '5 (Cinco dias)'), ('Sete', '7 (Sete dias)'), ('Quinze', '15 (Quinze dias)'), ('Trinta', '30 (Trinta dias)'), ('Sessenta', '60 (Sessenta dias)')], default='Sete', max_length=200, verbose_name='Validade da proposta')),
                ('CIF', models.BooleanField(default=False, verbose_name='CIF - frete e o seguro são pagos pelo fornecedor')),
                ('Prazo_de_Entrega', models.CharField(blank=True, choices=[('Imediato', 'Imediato'), ('Sete', '7 (Sete) dias'), ('Quinze', '15 (Quinze) dias'), ('Vinte', '20 (Vinte) dias'), ('Trinta', '30 (Trinta) dias'), ('Sessenta', '60 (Sessenta) dias')], default='Sete', max_length=200)),
                ('Frete', models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=15)),
                ('INSTALAÇÃO', models.BooleanField(default=False)),
                ('Valor_Instalação', models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=15)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente')),
            ],
            options={
                'verbose_name': 'Proposta',
                'verbose_name_plural': 'Propostas',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(default='/produtos/gerador.png', upload_to='produtos')),
                ('Tensão_Gerador', models.CharField(choices=[('220/127 V ', '220/127 V '), ('380/220 V', '380/220 V'), ('440/254 V', '440/254 V'), ('440/220 V - Monofásico', '440/220 V - Monofásico')], max_length=200)),
                ('aut_man_Gerador', models.CharField(choices=[('AUTOMATICO', 'Automático'), ('MANUAL', 'Manual')], max_length=200)),
                ('QTA_Gerador', models.CharField(blank=True, choices=[('Transferência em rampa', 'Transferência em rampa'), ('Transferência a seco', 'Transferência a seco')], max_length=200)),
                ('Controlador_Gerador', models.CharField(blank=True, choices=[('AGC150', 'AGC150'), ('AGC150 CORE', 'AGC150 CORE'), ('AGC150 HIBRIDY', 'AGC150 HIBRIDY'), ('AGC200', 'AGC200'), ('CGC400', 'CGC400'), ('4510', '4510'), ('4520', '4520'), ('7420', '7420'), ('8620', '8620'), ('8620', '8620'), ('8620', '8620')], default='CGC400', max_length=200)),
                ('Silenciador_Gerador', models.CharField(blank=True, choices=[('Silencioso Hospitalar', 'Silencioso Hospitalar'), ('Silencioso Industrial', 'Silencioso Industrial')], max_length=200)),
                ('Nivel_de_ruído', models.CharField(choices=[('65 dB(A) @ 1,5 metros ou 55 dB(A) @ 7,0 metros de distância', '65 dB(A) @ 1,5 metros ou 55 dB(A) @ 7,0 metros de distância'), ('70 dB(A) @ 1,5 metros ou 60 dB(A) @ 7,0 metros de distância', '70 dB(A) @ 1,5 metros ou 60 dB(A) @ 7,0 metros de distância'), ('75 dB(A) @ 1,5 metros ou 65 dB(A) @ 7,0 metros de distância', '75 dB(A) @ 1,5 metros ou 65 dB(A) @ 7,0 metros de distância'), ('80 dB(A) @ 1,5 metros ou 70 dB(A) @ 7,0 metros de distância', '80 dB(A) @ 1,5 metros ou 70 dB(A) @ 7,0 metros de distância'), ('85 dB(A) @ 1,5 metros ou 75 dB(A) @ 7,0 metros de distância', '85 dB(A) @ 1,5 metros ou 75 dB(A) @ 7,0 metros de distância')], default='85 dB(A) @ 1,5 metros ou 75 dB(A) @ 7,0 metros de distância', max_length=100, verbose_name='Nivel de ruído')),
                ('quantidade_Gerador', models.DecimalField(blank=True, decimal_places=0, max_digits=15)),
                ('valor_gerador', models.DecimalField(decimal_places=2, max_digits=15)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Motor')),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Proposta')),
            ],
        ),
    ]
